config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :users, only: :show
  resources :posts do
    resources :comments, only: :create
  end

  post 'like/:id' => 'likes#create', as: 'create_like'
  delete 'like/:id' => 'likes#destroy', as: 'destroy_like'
  post 'good/:id' => 'goods#create', as: 'create_good'
 delete 'good/:id' => 'goods#destroy', as: 'destroy_good'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true
  
  belongs_to :user
  belongs_to :post
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  validates :text, presence: true

  belongs_to :user
  has_one_attached :image
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :goods, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :goods, dependent: :destroy

  def liked_by?(post_id)
    likes.where(post_id: post_id).exists?
  end
  
  def gooded_by?(post_id)
    goods.where(post_id: post_id).exists?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_path(params[:post_id])
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  before_action :set_post, only: [:create, :destroy]

  def create
    Good.create(user_id: current_user.id, post_id: params[:id])
  end
  
  def destroy
    Good.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end
  
  private
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
 
  def create
    Like.create(user_id: current_user.id, post_id: params[:id])
  end
 
  def destroy
    Like.find_by(user_id: current_user.id, post_id: params[:id]).destroy
  end
 
  private
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :edit, :destroy]
  before_action :set_post, only: [:destroy, :edit, :update, :show]

  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    if current_user.id == @post.user_id
      @post.destroy
    else
      redirect_to root_path
    end
    redirect_to root_path
  end

  def edit
  end

  def update
    @post.update(post_params)
    if @post.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def show
    @comments = @post.comments.includes(:user)
    @comment = Comment.new
  end

  private

  def post_params
    params.require(:post).permit(:text, :image).merge(user_id: current_user.id)
  end
  
  def set_post
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @name = current_user.name
    @posts = current_user.posts
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goods/_good.html.erb
<% if user_signed_in? %>
 <% if current_user.gooded_by?(post.id) %>
   <td>
     <%= link_to destroy_good_path(post), method: :DELETE, remote: true do %>
       <i class="fa fa-heart unlike-btn"> いつもお疲れ様!</i> 
     <% end %> 
     <%= post.goods.count %>
   </td>
 <% else %>
   <td>
     <%= link_to create_good_path(post), method: :POST, remote: true do %>
       <i class="fa fa-heart like-btn"> いつもお疲れ様!</i>
     <% end %>
     <%= post.goods.count %>
   </td>
 <% end %>
<% end %>

app/views/goods/create.js.erb
$('#goods_buttons_<%= @post.id %>').html("<%= j(render partial: 'goods/good', locals: {post: @post}) %>");

app/views/goods/destroy.js.erb
$('#goods_buttons_<%= @post.id %>').html("<%= j(render partial: 'goods/good', locals: {post: @post}) %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelpEachOther</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css" integrity="sha384-Bfad6CLCknfcloXFOyFnlgtENryhrpZCe29RTifKEixXQZ38WheV+i/6YWSzkz3V" crossorigin="anonymous">
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light fixed-top" style="background-color: white;">
        <div class="container-fluid">
          <%= link_to image_tag("logo.PNG"), root_path, class:"navbar-brand" %>
          <form class="d-flex">
            <% if user_signed_in? %>
              <%= link_to "Post", new_post_path, class: "btn btn-outline-secondary mr-2" %>
              <%= link_to "My page", user_path(current_user.id), class: "btn btn-outline-secondary mr-2" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-outline-secondary mr-2" %>
            <% else %>
              <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-secondary mr-2" %>
              <%= link_to "Log in", new_user_session_path, class: "btn btn-outline-secondary mr-2" %>
            <% end %>
          </form>
        </div>
      </nav>
    </header>
  <%= yield %>
  </body>
</html>

app/views/likes/_like.html.erb
<% if user_signed_in? %>
 <% if current_user.liked_by?(post.id) %>
   <td>
     <%= link_to destroy_like_path(post), method: :DELETE, remote: true do %> 
       <i class="far fa-lightbulb unlight-btn"> 天才! </i>
     <% end %>
     <%= post.likes.count %>
   </td>
 <% else %>
    <td>
     <%= link_to create_like_path(post), method: :POST, remote: true do %> 
       <i class="far fa-lightbulb light-btn"> 天才! </i> 
     <% end %> 
     <%= post.likes.count %>
   </td>
 <% end %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @post.id %>').html("<%= j(render partial: 'likes/like', locals: {post: @post}) %>");

app/views/posts/edit.html.erb
<div class="jumbotron">
  <div class="col-md-4 offset-md-4">
    <div class="container">
      <h3 class="edit text-center">edit</h3>
      <%= form_with(model: @post, local: true) do |form| %>
        <div>
          <p>Image</p>
          <%= form.file_field :image %>
        </div>
        <div>
          <p>Text</p>
          <%= form.text_area :text, placeholder: "text", rows: "10", class: "form-control" %>
        </div>
        <div>
          <%= form.submit "SEND", class: "btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="card-columns">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Help Each Other とは？</h5>
          <p class="card-text">Help Each Other は、認知症の方を介護している人々が気軽に意見を交換したり、</p>
          <p class="card-text">介護の知恵などを発信し、互いに助け合うことができれば良いなという想いから生まれたSNSです。</p>
          <p class="card-text">大好きな母や父、祖父母を想い恩返しのつもりで介護をしていても、</p>
          <p class="card-text">毎日続く介護に疲弊してしまい笑顔を失ってしまうこともあると思います。</p>
          <p class="card-text">そんな時は、このアプリを開いてみんなで助け合い、</p>
          <p class="card-text">介護される人もする人もできる限りハッピーに過ごせるきっかけになれば嬉しいです。</p>
        </div>
      </div>

      <% @posts.each do |post| %>
        <%= link_to post_path(post.id) do %>
          <div class="card">
            <div class="card-img-top text-center">
              <%= image_tag post.image.variant(resize: '250x250') if post.image.attached? %>
            </div>
        <% end %>
            <div class="card-body">
              <% if user_signed_in? && current_user.id == post.user_id %>
                <p class="card-title"><%= link_to post.user.name, user_path(current_user.id), class: "editlink" %></p>
              <% else %>
                <p class="card-title"><%= post.user.name %></p>
              <% end %>
                <p class="card-text"><%= safe_join(post.text.split("\n"),tag(:br)) %></p>
                <%= link_to "Comment", post_path(post.id), class: "editlink" %>
              <div class="like-good">
                <div id="likes_buttons_<%= post.id %>" class="like">
                  <%= render partial: 'likes/like', locals: {post: post} %>
                </div>
                <div id="goods_buttons_<%= post.id %>" class="good">
                  <%= render partial: 'goods/good', locals: {post: post} %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="jumbotron">
  <div class="col-md-4 offset-md-4">
    <div class="container">
      <h3 class="post text-center">post</h3>
      <%= form_with(model: @post, local: true) do |form| %>
        <div>
          <p>Image</p>
          <%= form.file_field :image %>
        </div>
        <div>
          <p>Text</p>
          <%= form.text_area :text, placeholder: "text", rows: "10", class: "form-control" %>
        </div>
        <div>
          <%= form.submit "SEND", class: "btn btn-outline-secondary" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="card-columns">
      <div class="card">
        <div class="card-img-top text-center">
          <%= image_tag @post.image.variant(resize: '250x250') if @post.image.attached? %>
        </div>
        <div class="card-body">
          <% if user_signed_in? && current_user.id == @post.user_id %>
            <p class="card-title"><%= link_to @post.user.name, user_path(current_user.id), class: "editlink" %></p>
          <% else %>
            <p class="card-title"><%= @post.user.name %></p>
          <% end %>
            <p class="card-text"><%= safe_join(@post.text.split("\n"),tag(:br)) %></p>
            <div class="comment-form">
              <% if user_signed_in? %>
                <%= form_with model: [@post, @comment], id: "comment-form" do |f| %>
                  <%= f.text_area :text, rows: "1", class: "form-control comment-text"%>
                  <%= f.submit "comment", class: "btn btn-outline-secondary" %>
                <% end %>
              <% end %>
            </div>
            <div id="comments">
                <% @post.comments.each do |comment| %>
                  <div class="comment">
                    <p class="user-info"><%= comment.user.name %> ： <%= comment.text%></p>
                  </div>
                <% end %>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="jumbotron">
  <div class="row">
    <div class="card-columns">
    <p class="mypage"><%= @name %>'s page</p>
      <% @posts.each do |post| %>
        <div class="card">
          <div class="card-img-top text-center">
            <%= image_tag post.image.variant(resize: '250x250') if post.image.attached? %>
          </div>
          <div class="card-body">
            <p class="card-title"><%= link_to post.user.name, user_path(current_user.id), class: "editlink" %></p>
            <p class="card-text"><%= safe_join(post.text.split("\n"),tag(:br)) %></p>
            <div>
              <%= link_to "Comment", post_path(post.id), class: "editlink" %>
            </div>
              <% if user_signed_in? && current_user.id == post.user_id %>
                <%= link_to "Edit", edit_post_path(post.id), class: "editlink", method: :get %>
                <%= link_to "Delete", post_path(post.id), class: "editlink delete",  method: :delete %>
              <% else %>
              <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>